id: 68a8a3f2c172bc72066770e7
name: Tasks
isDeactivated: false
state: READY
errors: []
key: tasks
customized: false
revision: 59d1ddd5-5c08-4d0e-8317-ed015c353cac
universalFieldMappingId: 68a8a3f2c172bc720667707a
universalFieldMappingRevision: 342521fa-9f58-4a4d-b103-a4f6f9f7836d
integrationId: 68a8a3ebc172bc7206676e48
dataSourceKey: tasks
dataSourceId: 68a8a3f1c172bc7206676f77
direction: both
defaultImportValue:
  $var: $
defaultExportValue:
  $var: $
exportValue:
  content:
    $var: $.content
  project_id:
    $var: $.projectId
  due_string:
    $var: $.dueTime
  id:
    $var: $.id
importValue:
  id:
    $var: $.id
  content:
    $var: $.content
  projectId:
    $var: $.project_id
  parentTaskId:
    $var: $.parent_id
integration:
  id: 68a8a3ebc172bc7206676e48
  name: Todoist
  key: todoist
  uuid: fc9354af-da42-46ee-b0b4-eee5c7b169f9
  state: READY
  errors: []
  createdAt: '2025-08-22T17:07:55.952Z'
  updatedAt: '2025-08-22T17:08:00.161Z'
  isDeactivated: false
  logoUri: https://static.integration.app/connectors/todoist-connector/logo.png
  connectorId: 64d0ea29d8707ad2f865acb7
  connectorVersion: 1.0.5
  hasMissingParameters: false
  hasDocumentation: true
  hasOperations: false
  operationsCount: 0
  hasData: true
  dataCollectionsCount: 5
  hasEvents: false
  eventsCount: 0
  hasGlobalWebhooks: false
  hasUdm: true
  authType: oauth2
