id: 68a8a3f1c172bc7206676f5c
name: Tasks
isDeactivated: false
state: READY
errors: []
key: tasks
revision: cc032f68-6211-4c5e-b950-17452bcaf5bc
integrationId: 689f2bf000905568ab2f66dc
customized: false
universalDataSourceId: 68a8a3f1c172bc7206676f0a
universalDataSourceRevision: 1e77689d-61bf-43e9-a49c-c66d27640de5
collectionKey: deal-tasks
udm: tasks
defaultPath: /data/deal-tasks
integration:
  id: 689f2bf000905568ab2f66dc
  name: ActiveCampaign
  key: activecampaign
  uuid: fc32b9d4-29a1-47b0-96e0-43ffce815330
  state: READY
  errors: []
  createdAt: '2025-08-15T12:45:36.207Z'
  updatedAt: '2025-08-15T12:45:47.265Z'
  isDeactivated: false
  logoUri: https://static.integration.app/connectors/activecampaign-connector/logo.png
  connectorId: 6466783960f981f3ce6968ec
  connectorVersion: 1.0.3
  hasMissingParameters: false
  hasDocumentation: false
  hasOperations: true
  operationsCount: 106
  hasData: true
  dataCollectionsCount: 20
  hasEvents: false
  eventsCount: 0
  hasGlobalWebhooks: false
  hasUdm: true
  authType: client-credentials
