id: 68a8a3f1c172bc7206676f4a
name: Tasks
isDeactivated: false
state: READY
errors: []
key: tasks
revision: dd8ad0ab-f824-4bd0-8c04-0c1e5c8fdfb0
integrationId: 689f2bf000905568ab2f66e6
customized: false
universalDataSourceId: 68a8a3f1c172bc7206676f0a
universalDataSourceRevision: 1e77689d-61bf-43e9-a49c-c66d27640de5
collectionKey: tasks
udm: tasks
defaultPath: /data/tasks
integration:
  id: 689f2bf000905568ab2f66e6
  name: HubSpot
  key: hubspot
  uuid: 84deb162-bb46-4146-aede-f00a4306d9eb
  state: READY
  errors: []
  createdAt: '2025-08-15T12:45:36.263Z'
  updatedAt: '2025-08-15T12:45:49.165Z'
  isDeactivated: false
  logoUri: https://static.integration.app/connectors/hubspot/logo.png
  connectorId: 62471fad996d5c297ae43f5f
  connectorVersion: 1.8.0
  hasMissingParameters: false
  hasDocumentation: true
  hasOperations: true
  operationsCount: 646
  hasData: true
  dataCollectionsCount: 32
  hasEvents: true
  eventsCount: 37
  hasGlobalWebhooks: true
  hasUdm: true
  authType: oauth2
