id: 68a8a3f2c172bc72066770d0
name: Tasks
isDeactivated: false
state: READY
errors: []
key: tasks
customized: false
revision: 2e22bdcc-a470-4ad2-a89a-a38ec279999c
universalFieldMappingId: 68a8a3f2c172bc720667707a
universalFieldMappingRevision: 342521fa-9f58-4a4d-b103-a4f6f9f7836d
integrationId: 689f2bf000905568ab2f66d8
dataSourceKey: tasks
dataSourceId: 68a8a3f1c172bc7206676f62
direction: both
defaultImportValue:
  $var: $
defaultExportValue:
  $var: $
exportValue:
  id:
    $var: $.id
  Owner:
    id:
      $var: $.ownerId
  Subject:
    $var: $.subject
  Due_Date:
    $var: $.dueTime
  Who_Id:
    id:
      $var: $.contactId
  What_Id:
    $case:
      cases:
        - filter:
            $eval:
              $var: $.companyId
            isNotEmpty: true
          value:
            type: Accounts
            id:
              $var: $.companyId
        - filter:
            $eval:
              $var: $.dealId
            isNotEmpty: true
          value:
            type: Deals
            id:
              $var: $.dealId
        - filter:
            $eval:
              $var: $.leadId
            isNotEmpty: true
          value:
            type: Leads
            id:
              $var: $.leadId
  Status:
    $var: $.status
  Priority:
    $var: $.priority
  Created_By:
    id:
      $var: $.createdBy
  Modified_By:
    id:
      $var: $.updatedBy
  Created_Time:
    $var: $.createdTime
  Modified_Time:
    $var: $.updatedTime
  Closed_Time:
    $var: $.endTime
  Description:
    $var: $.content
importValue:
  id:
    $var: $.id
  title:
    $var: $.Subject
  description:
    $var: $.Description
  status:
    $var: $.Status
  contactId:
    $var: $.Who_Id.id
  companyId:
    $case:
      cases:
        - filter:
            $eval:
              $var: $.What_Id.type
            is: Accounts
          value:
            $var: $.What_Id.id
  dealId:
    $case:
      cases:
        - filter:
            $eval:
              $var: $.What_Id.type
            is: Deals
          value:
            $var: $.What_Id.id
  leadId:
    $case:
      cases:
        - filter:
            $eval:
              $var: $.What_Id.type
            is: Leads
          value:
            $var: $.What_Id.id
  ownerId:
    $var: $.Owner.id
  createdTime:
    $var: $.Created_Time
  updatedTime:
    $var: $.Modified_Time
  createdBy:
    $var: $.Created_By.id
  updatedBy:
    $var: $.Modified_By.id
  endTime:
    $var: $.Closed_Time
  dueTime:
    $var: $.Due_Date
  subject:
    $var: $.Subject
  content:
    $var: $.Description
  priority:
    $var: $.Priority
  startTime:
    $var: $.Closed_Time
  assigneeId:
    $var: $.Owner.id
integration:
  id: 689f2bf000905568ab2f66d8
  name: Zoho CRM
  key: zoho-crm
  uuid: ccf1c7bb-8266-4e1a-bca9-d5ac178ab7bf
  state: READY
  errors: []
  createdAt: '2025-08-15T12:45:36.205Z'
  updatedAt: '2025-08-15T12:45:46.121Z'
  isDeactivated: false
  logoUri: https://static.integration.app/connectors/zoho-crm/logo.png
  connectorId: 64a158e7d2605720d232e07b
  connectorVersion: 2.2.0
  hasMissingParameters: false
  hasDocumentation: false
  hasOperations: true
  operationsCount: 569
  hasData: true
  dataCollectionsCount: 20
  hasEvents: false
  eventsCount: 0
  hasGlobalWebhooks: false
  hasUdm: true
  authType: oauth2
