id: 68a8a3f1c172bc7206676f50
name: Tasks
isDeactivated: false
state: READY
errors: []
key: tasks
revision: e904fa56-cf2c-427d-82cd-030b3ce65fa5
integrationId: 68a8a3ebc172bc7206676e44
customized: false
universalDataSourceId: 68a8a3f1c172bc7206676f0a
universalDataSourceRevision: 1e77689d-61bf-43e9-a49c-c66d27640de5
collectionKey: tasks
udm: tasks
defaultPath: /data/tasks
integration:
  id: 68a8a3ebc172bc7206676e44
  name: Clickup
  key: clickup
  uuid: af6fad15-3a7c-441e-89fe-90264262a5f5
  state: READY
  errors: []
  createdAt: '2025-08-22T17:07:55.950Z'
  updatedAt: '2025-08-22T17:08:00.685Z'
  isDeactivated: false
  logoUri: https://static.integration.app/connectors/clickup/logo.png
  connectorId: 64359f80986ed1caadafa638
  connectorVersion: 1.2.3
  hasMissingParameters: false
  hasDocumentation: false
  hasOperations: true
  operationsCount: 11
  hasData: true
  dataCollectionsCount: 9
  hasEvents: true
  eventsCount: 28
  hasGlobalWebhooks: false
  hasUdm: true
  authType: oauth2
