id: 68a8a3f2c172bc72066770d5
name: Tasks
isDeactivated: false
state: READY
errors: []
key: tasks
customized: false
revision: 66d9c345-f7d8-4169-a5c7-b9c2c549a654
universalFieldMappingId: 68a8a3f2c172bc720667707a
universalFieldMappingRevision: 342521fa-9f58-4a4d-b103-a4f6f9f7836d
integrationId: 68a8a3ebc172bc7206676e44
dataSourceKey: tasks
dataSourceId: 68a8a3f1c172bc7206676f50
direction: both
defaultImportValue:
  $var: $
defaultExportValue:
  $var: $
exportValue:
  name:
    $var: $.subject
  parent:
    $var: $.parentTaskId
  text_content:
    $var: $.content
  status_id:
    $var: $.status
  status:
    status:
      $var: $.status
  date_created:
    $var: $.createdTime
  date_updated:
    $var: $.updatedTime
  creator: {}
  assignees:
    - $var: $.assigneeId
  priority:
    $var: $.priority
  due_date:
    $var: $.dueTime
  start_date:
    $var: $.startTime
  time_estimate:
    $var: $.endTime
  watchers:
    $iterate:
      source:
        $var: $.followerIds
      item:
        id:
          $var: $.item
importValue:
  id:
    $var: $.id
  subject:
    $var: $.name
  content:
    $var: $.text_content
  status:
    $var: $.status.status
  priority:
    $var: $.priority
  assigneeId:
    $var: $.assignees[0]
  parentTaskId:
    $var: $.parent
  dueTime:
    $var: $.due_date
  startTime:
    $var: $.start_date
  endTime:
    $var: $.time_estimate
  createdTime:
    $var: $.date_created
  createdBy:
    $var: $.creator.id
  updatedTime:
    $var: $.date_updated
  followerIds:
    $iterate:
      source:
        $var: $.watchers
      item:
        $var: $.item.id
  ownerId:
    $var: $.assignees[0]
integration:
  id: 68a8a3ebc172bc7206676e44
  name: Clickup
  key: clickup
  uuid: af6fad15-3a7c-441e-89fe-90264262a5f5
  state: READY
  errors: []
  createdAt: '2025-08-22T17:07:55.950Z'
  updatedAt: '2025-08-22T17:08:00.685Z'
  isDeactivated: false
  logoUri: https://static.integration.app/connectors/clickup/logo.png
  connectorId: 64359f80986ed1caadafa638
  connectorVersion: 1.2.3
  hasMissingParameters: false
  hasDocumentation: false
  hasOperations: true
  operationsCount: 11
  hasData: true
  dataCollectionsCount: 9
  hasEvents: true
  eventsCount: 28
  hasGlobalWebhooks: false
  hasUdm: true
  authType: oauth2
